package com.example.myvue.model;

import java.util.Date;

public class CompanyQuotePrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_quote_price.quote_id
     *
     * @mbggenerated Wed May 02 07:59:15 CST 2018
     */
    private Long quoteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_quote_price.company_name
     *
     * @mbggenerated Wed May 02 07:59:15 CST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_quote_price.company_value
     *
     * @mbggenerated Wed May 02 07:59:15 CST 2018
     */
    private Double companyValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_quote_price.create_time
     *
     * @mbggenerated Wed May 02 07:59:15 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_quote_price.quote_id
     *
     * @return the value of company_quote_price.quote_id
     *
     * @mbggenerated Wed May 02 07:59:15 CST 2018
     */
    public Long getQuoteId() {
        return quoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_quote_price.quote_id
     *
     * @param quoteId the value for company_quote_price.quote_id
     *
     * @mbggenerated Wed May 02 07:59:15 CST 2018
     */
    public void setQuoteId(Long quoteId) {
        this.quoteId = quoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_quote_price.company_name
     *
     * @return the value of company_quote_price.company_name
     *
     * @mbggenerated Wed May 02 07:59:15 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_quote_price.company_name
     *
     * @param companyName the value for company_quote_price.company_name
     *
     * @mbggenerated Wed May 02 07:59:15 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_quote_price.company_value
     *
     * @return the value of company_quote_price.company_value
     *
     * @mbggenerated Wed May 02 07:59:15 CST 2018
     */
    public Double getCompanyValue() {
        return companyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_quote_price.company_value
     *
     * @param companyValue the value for company_quote_price.company_value
     *
     * @mbggenerated Wed May 02 07:59:15 CST 2018
     */
    public void setCompanyValue(Double companyValue) {
        this.companyValue = companyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_quote_price.create_time
     *
     * @return the value of company_quote_price.create_time
     *
     * @mbggenerated Wed May 02 07:59:15 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_quote_price.create_time
     *
     * @param createTime the value for company_quote_price.create_time
     *
     * @mbggenerated Wed May 02 07:59:15 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}