package com.example.myvue.model;

public class ConsumeHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_history.consume_history_id
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    private Long consumeHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_history.phone
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_history.account_id
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    private Long accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_history.consume_type
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    private Integer consumeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_history.monetary
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    private Integer monetary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_history.consumer_id
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    private Long consumerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_history.pay_channel
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    private Integer payChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_history.consume_time
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    private String consumeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_history.consume_history_id
     *
     * @return the value of consume_history.consume_history_id
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    public Long getConsumeHistoryId() {
        return consumeHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_history.consume_history_id
     *
     * @param consumeHistoryId the value for consume_history.consume_history_id
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    public void setConsumeHistoryId(Long consumeHistoryId) {
        this.consumeHistoryId = consumeHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_history.phone
     *
     * @return the value of consume_history.phone
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_history.phone
     *
     * @param phone the value for consume_history.phone
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_history.account_id
     *
     * @return the value of consume_history.account_id
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_history.account_id
     *
     * @param accountId the value for consume_history.account_id
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_history.consume_type
     *
     * @return the value of consume_history.consume_type
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    public Integer getConsumeType() {
        return consumeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_history.consume_type
     *
     * @param consumeType the value for consume_history.consume_type
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    public void setConsumeType(Integer consumeType) {
        this.consumeType = consumeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_history.monetary
     *
     * @return the value of consume_history.monetary
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    public Integer getMonetary() {
        return monetary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_history.monetary
     *
     * @param monetary the value for consume_history.monetary
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    public void setMonetary(Integer monetary) {
        this.monetary = monetary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_history.consumer_id
     *
     * @return the value of consume_history.consumer_id
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    public Long getConsumerId() {
        return consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_history.consumer_id
     *
     * @param consumerId the value for consume_history.consumer_id
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    public void setConsumerId(Long consumerId) {
        this.consumerId = consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_history.pay_channel
     *
     * @return the value of consume_history.pay_channel
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    public Integer getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_history.pay_channel
     *
     * @param payChannel the value for consume_history.pay_channel
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    public void setPayChannel(Integer payChannel) {
        this.payChannel = payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_history.consume_time
     *
     * @return the value of consume_history.consume_time
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    public String getConsumeTime() {
        return consumeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_history.consume_time
     *
     * @param consumeTime the value for consume_history.consume_time
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    public void setConsumeTime(String consumeTime) {
        this.consumeTime = consumeTime == null ? null : consumeTime.trim();
    }
}