package com.example.myvue.model;

public class PersonToCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_to_company.id
     *
     * @mbggenerated Sun Apr 22 17:06:00 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_to_company.user_id
     *
     * @mbggenerated Sun Apr 22 17:06:00 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_to_company.company_id
     *
     * @mbggenerated Sun Apr 22 17:06:00 CST 2018
     */
    private Long companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_to_company.id
     *
     * @return the value of person_to_company.id
     *
     * @mbggenerated Sun Apr 22 17:06:00 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_to_company.id
     *
     * @param id the value for person_to_company.id
     *
     * @mbggenerated Sun Apr 22 17:06:00 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_to_company.user_id
     *
     * @return the value of person_to_company.user_id
     *
     * @mbggenerated Sun Apr 22 17:06:00 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_to_company.user_id
     *
     * @param userId the value for person_to_company.user_id
     *
     * @mbggenerated Sun Apr 22 17:06:00 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_to_company.company_id
     *
     * @return the value of person_to_company.company_id
     *
     * @mbggenerated Sun Apr 22 17:06:00 CST 2018
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_to_company.company_id
     *
     * @param companyId the value for person_to_company.company_id
     *
     * @mbggenerated Sun Apr 22 17:06:00 CST 2018
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
}