package com.example.myvue.model;

public class PersonToPhone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_to_phone.id
     *
     * @mbggenerated Sun Apr 22 17:06:11 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_to_phone.user_id
     *
     * @mbggenerated Sun Apr 22 17:06:11 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_to_phone.phone
     *
     * @mbggenerated Sun Apr 22 17:06:11 CST 2018
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_to_phone.id
     *
     * @return the value of person_to_phone.id
     *
     * @mbggenerated Sun Apr 22 17:06:11 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_to_phone.id
     *
     * @param id the value for person_to_phone.id
     *
     * @mbggenerated Sun Apr 22 17:06:11 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_to_phone.user_id
     *
     * @return the value of person_to_phone.user_id
     *
     * @mbggenerated Sun Apr 22 17:06:11 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_to_phone.user_id
     *
     * @param userId the value for person_to_phone.user_id
     *
     * @mbggenerated Sun Apr 22 17:06:11 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_to_phone.phone
     *
     * @return the value of person_to_phone.phone
     *
     * @mbggenerated Sun Apr 22 17:06:11 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_to_phone.phone
     *
     * @param phone the value for person_to_phone.phone
     *
     * @mbggenerated Sun Apr 22 17:06:11 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}