package com.example.myvue.model;

public class ProQuotePrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_quote_price.id
     *
     * @mbggenerated Wed Apr 25 08:32:38 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_quote_price.pro_quote_price_id
     *
     * @mbggenerated Wed Apr 25 08:32:38 CST 2018
     */
    private Long proQuotePriceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_quote_price.id
     *
     * @return the value of pro_quote_price.id
     *
     * @mbggenerated Wed Apr 25 08:32:38 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_quote_price.id
     *
     * @param id the value for pro_quote_price.id
     *
     * @mbggenerated Wed Apr 25 08:32:38 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_quote_price.pro_quote_price_id
     *
     * @return the value of pro_quote_price.pro_quote_price_id
     *
     * @mbggenerated Wed Apr 25 08:32:38 CST 2018
     */
    public Long getProQuotePriceId() {
        return proQuotePriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_quote_price.pro_quote_price_id
     *
     * @param proQuotePriceId the value for pro_quote_price.pro_quote_price_id
     *
     * @mbggenerated Wed Apr 25 08:32:38 CST 2018
     */
    public void setProQuotePriceId(Long proQuotePriceId) {
        this.proQuotePriceId = proQuotePriceId;
    }
}