package com.example.myvue.model;

import com.alibaba.fastjson.JSONObject;

import java.util.List;

public class QuotePrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote_price.quote_price_id
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    private Long quotePriceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote_price.consumer_id
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    private Long consumerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote_price.project_number
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    private String projectNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote_price.quote_id
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    private Long quoteId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote_price.quote_price_id
     *
     * @return the value of quote_price.quote_price_id
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    public Long getQuotePriceId() {
        return quotePriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote_price.quote_price_id
     *
     * @param quotePriceId the value for quote_price.quote_price_id
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    public void setQuotePriceId(Long quotePriceId) {
        this.quotePriceId = quotePriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote_price.consumer_id
     *
     * @return the value of quote_price.consumer_id
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    public Long getConsumerId() {
        return consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote_price.consumer_id
     *
     * @param consumerId the value for quote_price.consumer_id
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    public void setConsumerId(Long consumerId) {
        this.consumerId = consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote_price.project_number
     *
     * @return the value of quote_price.project_number
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    public String getProjectNumber() {
        return projectNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote_price.project_number
     *
     * @param projectNumber the value for quote_price.project_number
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    public void setProjectNumber(String projectNumber) {
        this.projectNumber = projectNumber == null ? null : projectNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote_price.quote_id
     *
     * @return the value of quote_price.quote_id
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    public Long getQuoteId() {
        return quoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote_price.quote_id
     *
     * @param quoteId the value for quote_price.quote_id
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    public void setQuoteId(Long quoteId) {
        this.quoteId = quoteId;
    }


    private List<CompanyQuotePrice> companyQuotePriceList;

    public List<CompanyQuotePrice> getCompanyQuotePriceList() {
        return companyQuotePriceList;
    }

    public void setCompanyQuotePriceList(List<CompanyQuotePrice> companyQuotePriceList) {
        this.companyQuotePriceList = companyQuotePriceList;
    }

    public  QuotePrice generator(JSONObject reqObj){
        this.setConsumerId(reqObj.getLong("consumerId"));
        this.setProjectNumber(reqObj.getString("projectNumber"));
        this.setCompanyQuotePriceList(reqObj.getJSONArray("comitData").toJavaList(CompanyQuotePrice.class));
        return this;
    }
}