package com.example.myvue.model;

import java.math.BigDecimal;

public class ShouldQuotePrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column should_quote_price.shoule_price_id
     *
     * @mbggenerated Wed Apr 25 08:41:56 CST 2018
     */
    private Long shoulePriceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column should_quote_price.should_price
     *
     * @mbggenerated Wed Apr 25 08:41:56 CST 2018
     */
    private BigDecimal shouldPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column should_quote_price.project_number
     *
     * @mbggenerated Wed Apr 25 08:41:56 CST 2018
     */
    private String projectNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column should_quote_price.consumer_id
     *
     * @mbggenerated Wed Apr 25 08:41:56 CST 2018
     */
    private Long consumerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column should_quote_price.create_time
     *
     * @mbggenerated Wed Apr 25 08:41:56 CST 2018
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column should_quote_price.shoule_price_id
     *
     * @return the value of should_quote_price.shoule_price_id
     *
     * @mbggenerated Wed Apr 25 08:41:56 CST 2018
     */
    public Long getShoulePriceId() {
        return shoulePriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column should_quote_price.shoule_price_id
     *
     * @param shoulePriceId the value for should_quote_price.shoule_price_id
     *
     * @mbggenerated Wed Apr 25 08:41:56 CST 2018
     */
    public void setShoulePriceId(Long shoulePriceId) {
        this.shoulePriceId = shoulePriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column should_quote_price.should_price
     *
     * @return the value of should_quote_price.should_price
     *
     * @mbggenerated Wed Apr 25 08:41:56 CST 2018
     */
    public BigDecimal getShouldPrice() {
        return shouldPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column should_quote_price.should_price
     *
     * @param shouldPrice the value for should_quote_price.should_price
     *
     * @mbggenerated Wed Apr 25 08:41:56 CST 2018
     */
    public void setShouldPrice(BigDecimal shouldPrice) {
        this.shouldPrice = shouldPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column should_quote_price.project_number
     *
     * @return the value of should_quote_price.project_number
     *
     * @mbggenerated Wed Apr 25 08:41:56 CST 2018
     */
    public String getProjectNumber() {
        return projectNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column should_quote_price.project_number
     *
     * @param projectNumber the value for should_quote_price.project_number
     *
     * @mbggenerated Wed Apr 25 08:41:56 CST 2018
     */
    public void setProjectNumber(String projectNumber) {
        this.projectNumber = projectNumber == null ? null : projectNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column should_quote_price.consumer_id
     *
     * @return the value of should_quote_price.consumer_id
     *
     * @mbggenerated Wed Apr 25 08:41:56 CST 2018
     */
    public Long getConsumerId() {
        return consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column should_quote_price.consumer_id
     *
     * @param consumerId the value for should_quote_price.consumer_id
     *
     * @mbggenerated Wed Apr 25 08:41:56 CST 2018
     */
    public void setConsumerId(Long consumerId) {
        this.consumerId = consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column should_quote_price.create_time
     *
     * @return the value of should_quote_price.create_time
     *
     * @mbggenerated Wed Apr 25 08:41:56 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column should_quote_price.create_time
     *
     * @param createTime the value for should_quote_price.create_time
     *
     * @mbggenerated Wed Apr 25 08:41:56 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}