package com.example.myvue.model;

public class UserCompanyId {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_id.company_id
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_id.company_name
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_id.company_account_id
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    private Long companyAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_id.authory_type
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    private Integer authoryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_id.company_address
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_id.company_real_name
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    private String companyRealName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_id.manager_phone
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    private String managerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_id.status
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_id.company_id
     *
     * @return the value of user_company_id.company_id
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_id.company_id
     *
     * @param companyId the value for user_company_id.company_id
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_id.company_name
     *
     * @return the value of user_company_id.company_name
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_id.company_name
     *
     * @param companyName the value for user_company_id.company_name
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_id.company_account_id
     *
     * @return the value of user_company_id.company_account_id
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    public Long getCompanyAccountId() {
        return companyAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_id.company_account_id
     *
     * @param companyAccountId the value for user_company_id.company_account_id
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    public void setCompanyAccountId(Long companyAccountId) {
        this.companyAccountId = companyAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_id.authory_type
     *
     * @return the value of user_company_id.authory_type
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    public Integer getAuthoryType() {
        return authoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_id.authory_type
     *
     * @param authoryType the value for user_company_id.authory_type
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    public void setAuthoryType(Integer authoryType) {
        this.authoryType = authoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_id.company_address
     *
     * @return the value of user_company_id.company_address
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_id.company_address
     *
     * @param companyAddress the value for user_company_id.company_address
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_id.company_real_name
     *
     * @return the value of user_company_id.company_real_name
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    public String getCompanyRealName() {
        return companyRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_id.company_real_name
     *
     * @param companyRealName the value for user_company_id.company_real_name
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    public void setCompanyRealName(String companyRealName) {
        this.companyRealName = companyRealName == null ? null : companyRealName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_id.manager_phone
     *
     * @return the value of user_company_id.manager_phone
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    public String getManagerPhone() {
        return managerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_id.manager_phone
     *
     * @param managerPhone the value for user_company_id.manager_phone
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    public void setManagerPhone(String managerPhone) {
        this.managerPhone = managerPhone == null ? null : managerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_id.status
     *
     * @return the value of user_company_id.status
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_id.status
     *
     * @param status the value for user_company_id.status
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}