package com.example.myvue.model;

public class UserPersonObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_person_object.user_id
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_person_object.phone
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_person_object.user_name
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_person_object.person_account_id
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    private Long personAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_person_object.authory_type
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    private Integer authoryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_person_object.id_card_num
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    private String idCardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_person_object.status
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_person_object.user_id
     *
     * @return the value of user_person_object.user_id
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_person_object.user_id
     *
     * @param userId the value for user_person_object.user_id
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_person_object.phone
     *
     * @return the value of user_person_object.phone
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_person_object.phone
     *
     * @param phone the value for user_person_object.phone
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_person_object.user_name
     *
     * @return the value of user_person_object.user_name
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_person_object.user_name
     *
     * @param userName the value for user_person_object.user_name
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_person_object.person_account_id
     *
     * @return the value of user_person_object.person_account_id
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    public Long getPersonAccountId() {
        return personAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_person_object.person_account_id
     *
     * @param personAccountId the value for user_person_object.person_account_id
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    public void setPersonAccountId(Long personAccountId) {
        this.personAccountId = personAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_person_object.authory_type
     *
     * @return the value of user_person_object.authory_type
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    public Integer getAuthoryType() {
        return authoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_person_object.authory_type
     *
     * @param authoryType the value for user_person_object.authory_type
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    public void setAuthoryType(Integer authoryType) {
        this.authoryType = authoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_person_object.id_card_num
     *
     * @return the value of user_person_object.id_card_num
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    public String getIdCardNum() {
        return idCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_person_object.id_card_num
     *
     * @param idCardNum the value for user_person_object.id_card_num
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    public void setIdCardNum(String idCardNum) {
        this.idCardNum = idCardNum == null ? null : idCardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_person_object.status
     *
     * @return the value of user_person_object.status
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_person_object.status
     *
     * @param status the value for user_person_object.status
     *
     * @mbggenerated Sun Apr 22 17:07:01 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}