package com.example.myvue.dao;

import com.example.myvue.model.Account;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Apr 22 17:04:52 CST 2018
     */
    int deleteByPrimaryKey(Long accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Apr 22 17:04:52 CST 2018
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Apr 22 17:04:52 CST 2018
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Apr 22 17:04:52 CST 2018
     */
    Account selectByPrimaryKey(Long accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Apr 22 17:04:52 CST 2018
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Apr 22 17:04:52 CST 2018
     */
    int updateByPrimaryKey(Account record);
}