package com.example.myvue.dao;

import com.example.myvue.model.AuthoryManage;
import org.springframework.stereotype.Service;


public interface AuthoryManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authory_manage
     *
     * @mbggenerated Sun Apr 22 17:05:35 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authory_manage
     *
     * @mbggenerated Sun Apr 22 17:05:35 CST 2018
     */
    int insert(AuthoryManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authory_manage
     *
     * @mbggenerated Sun Apr 22 17:05:35 CST 2018
     */
    int insertSelective(AuthoryManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authory_manage
     *
     * @mbggenerated Sun Apr 22 17:05:35 CST 2018
     */
    AuthoryManage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authory_manage
     *
     * @mbggenerated Sun Apr 22 17:05:35 CST 2018
     */
    int updateByPrimaryKeySelective(AuthoryManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authory_manage
     *
     * @mbggenerated Sun Apr 22 17:05:35 CST 2018
     */
    int updateByPrimaryKey(AuthoryManage record);
}