package com.example.myvue.dao;

import com.example.myvue.model.ConsumeHistory;
import org.springframework.stereotype.Service;


public interface ConsumeHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consume_history
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    int deleteByPrimaryKey(Long consumeHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consume_history
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    int insert(ConsumeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consume_history
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    int insertSelective(ConsumeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consume_history
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    ConsumeHistory selectByPrimaryKey(Long consumeHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consume_history
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    int updateByPrimaryKeySelective(ConsumeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consume_history
     *
     * @mbggenerated Sun Apr 22 17:05:50 CST 2018
     */
    int updateByPrimaryKey(ConsumeHistory record);
}