package com.example.myvue.dao;

import com.example.myvue.model.PersonToPhone;

public interface PersonToPhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_to_phone
     *
     * @mbggenerated Sun Apr 22 17:06:11 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_to_phone
     *
     * @mbggenerated Sun Apr 22 17:06:11 CST 2018
     */
    int insert(PersonToPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_to_phone
     *
     * @mbggenerated Sun Apr 22 17:06:11 CST 2018
     */
    int insertSelective(PersonToPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_to_phone
     *
     * @mbggenerated Sun Apr 22 17:06:11 CST 2018
     */
    PersonToPhone selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_to_phone
     *
     * @mbggenerated Sun Apr 22 17:06:11 CST 2018
     */
    int updateByPrimaryKeySelective(PersonToPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_to_phone
     *
     * @mbggenerated Sun Apr 22 17:06:11 CST 2018
     */
    int updateByPrimaryKey(PersonToPhone record);
}