package com.example.myvue.dao;

import com.example.myvue.model.QuotePrice;
import org.springframework.stereotype.Service;

import java.util.List;


public interface QuotePriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_price
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    int deleteByPrimaryKey(Long quotePriceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_price
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    int insert(QuotePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_price
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    int insertSelective(QuotePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_price
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    QuotePrice selectByPrimaryKey(Long quotePriceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_price
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    int updateByPrimaryKeySelective(QuotePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_price
     *
     * @mbggenerated Thu Apr 26 08:17:45 CST 2018
     */
    int updateByPrimaryKey(QuotePrice record);

    void insertBatch(List<QuotePrice> quotePrices);
}