package com.example.myvue.dao;

import com.example.myvue.model.UserCompanyId;
import org.springframework.stereotype.Service;


public interface UserCompanyIdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_id
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    int deleteByPrimaryKey(Long companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_id
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    int insert(UserCompanyId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_id
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    int insertSelective(UserCompanyId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_id
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    UserCompanyId selectByPrimaryKey(Long companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_id
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    int updateByPrimaryKeySelective(UserCompanyId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_id
     *
     * @mbggenerated Sun Apr 22 17:06:52 CST 2018
     */
    int updateByPrimaryKey(UserCompanyId record);
}